package jyt.geconomicus.helper;

import java.io.Serializable;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.TableGenerator;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlTransient;

/**
 * A player in the game.
 * @author jytou
 *
 * NOTE DE MIGRATION (2026) : logique inchangée depuis la version originale de jytou
 * (https://gitlab.com/jytou/geconomicus_helper). Seules les annotations jakarta.persistence/jakarta.xml.bind
 * ont été mises à jour (voir docs/03-architecture-technique.md).
 */
@Entity
public class Player implements Serializable
{
	// The ID is automatically generated by EclipseLink.
	@TableGenerator(
		name="playerGen",
		table="ID_GEN",
		pkColumnName="GEN_KEY",
		valueColumnName="GEN_VALUE",
		pkColumnValue="PLAYER_ID",
		allocationSize=1
	)
	@XmlTransient
	@GeneratedValue(strategy=GenerationType.TABLE, generator="playerGen")
	@Id
	private Integer id;

	// The game in which this player is playing
	@XmlIDREF
	@ManyToOne
	@JoinColumn(nullable=false)
	private Game game;

	// The name of the player
	@XmlID
	private String name;

	// True if the player is active in the game (has joined and did not quit), false otherwise.
	private boolean active;
	// The current debt of the player towards the bank
	private int curDebt;
	// The current interest owed by the player towards the bank. Note that we could easily
	// remove the debt field since we already would know from the interest how much he owes.
	// Nice optimization idea.
	private int curInterest;
	// True if the player has visited the bank during the current turn/round or not.
	private boolean visitedBank;

	// Troc uniquement (voir plugins/troc/manifest.json, Game.MONEY_TROC) : nombre
	// d'objets actuellement possédés. Mis à jour en direct à chaque échange (voir
	// Event.applyEvent, cas GOODS_TRADE) plutôt que ressaisi manuellement comme
	// l'inventaire des autres systèmes - le logiciel le connaît déjà. Retour
	// utilisateur : uniquement des transactions d'échange - jamais de don sans
	// contrepartie, jamais de monnaie ni de jeton (les échanges de service et le
	// temps de vie ont été retirés après un premier essai).
	//
	// Reste un simple TOTAL affiché tel quel (nombre d'objets en main, toutes
	// valeurs confondues) - depuis le 28/08/2026 (retour utilisateur : "il faut
	// reprendre le système de valeur 4x pour que les joueurs cherchent encore à
	// faire des carrés"), la RICHESSE, elle, ne se calcule plus à partir de ce
	// total mais des trois champs par niveau ci-dessous (voir
	// StatsService.computeGain, cas MONEY_TROC) - un carré (4 objets d'un niveau
	// donné) reconstitué en 1 objet du niveau supérieur ne change donc plus la
	// richesse du joueur (4×1 = 1×4), contrairement à avant où "un objet compte
	// pour 1 quel que soit son niveau" retirait tout intérêt économique au
	// carré. goodsCount reste maintenu en parallèle (toujours = weakGoods +
	// mediumGoods + strongGoods) uniquement pour ne rien casser côté affichage
	// (tableau de bord, graphique de répartition...), qui n'a besoin que du
	// total, jamais du détail par niveau.
	private int goodsCount;
	private int weakGoods;
	private int mediumGoods;
	private int strongGoods;

	// --- Étape 3, Phase B : identité et avatar choisis par le joueur lui-même
	// lors de l'auto-inscription depuis son smartphone (écran "Créez votre avatar").
	// Champs volontairement optionnels (null par défaut) : un joueur ajouté
	// manuellement par l'animateur (app Swing ou bouton "+ Joueur" du dashboard web)
	// n'a pas besoin de les renseigner, cette fonctionnalité reste additive.
	// avatarConfigJson stocke un petit objet JSON (forme du visage, couleur de peau,
	// style de cheveux, accessoire...) plutôt que des colonnes dédiées par attribut :
	// le jeu d'options d'avatar est encore amené à évoluer, une colonne JSON évite
	// une migration de schéma à chaque ajustement de la palette de personnalisation.
	private String avatarConfigJson;
	// Couleur d'identité choisie par le joueur (code hex, ex. "#7C3AED"), utilisée
	// pour le distinguer visuellement dans l'app mobile (bordures, badges...).
	private String favoriteColor;
	// Âge "de personnage" choisi par le joueur à l'inscription (ex. 24 ans) - purement
	// déclaratif/cosmétique, à ne pas confondre avec l'âge en tours de jeu déjà
	// calculé ailleurs (Dtos.GameDetailDto), qui reflète le nombre de tours écoulés
	// depuis la dernière naissance/renaissance.
	private Integer declaredAge;

	// Remonté par un utilisateur : jeton d'accès individuel, propre à ce joueur -
	// uniquement généré quand la protection par code est activée (voir
	// AppSettings.protectionEnabled et Game.pin). Donne un accès limité aux
	// actions concernant CE joueur précis (voir son propre inventaire, proposer
	// un échange le concernant), jamais un accès aux autres joueurs ni aux
	// actions d'administration réservées au PIN de partie. Généré une fois à la
	// création du joueur, ne change jamais ensuite (un lien/QR code partagé au
	// joueur reste valable toute la partie).
	private String accessToken;

	// Used by EclipseLink to instantiate empty objects.
	@SuppressWarnings("unused")
	private Player()
	{
		super();
	}

	/**
	 * Create a new player in this game
	 * @param pGame
	 * @param pName
	 */
	public Player(Game pGame, String pName)
	{
		super();
		game = pGame;
		game.addPlayer(this);
		name = pName;
		active = false;
		curDebt = 0;
		curInterest = 0;
		visitedBank = true;
		// Sans effet pour la monnaie dette/libre (reste à 0, jamais lu) - voir
		// Game.MONEY_TROC. Les cartes de départ sont toutes de niveau faible
		// (convention identique à dette/libre, où la dotation initiale ne
		// comporte jamais de cartes moyennes/fortes).
		goodsCount = pGame.getStartingGoods();
		weakGoods = pGame.getStartingGoods();
	}

	public String getAvatarConfigJson()
	{
		return avatarConfigJson;
	}

	public void setAvatarConfigJson(final String pAvatarConfigJson)
	{
		avatarConfigJson = pAvatarConfigJson;
	}

	public String getFavoriteColor()
	{
		return favoriteColor;
	}

	public void setFavoriteColor(final String pFavoriteColor)
	{
		favoriteColor = pFavoriteColor;
	}

	public Integer getDeclaredAge()
	{
		return declaredAge;
	}

	public void setDeclaredAge(final Integer pDeclaredAge)
	{
		declaredAge = pDeclaredAge;
	}

	public String getAccessToken()
	{
		return accessToken;
	}

	public void setAccessToken(final String pAccessToken)
	{
		accessToken = pAccessToken;
	}

	public boolean isActive()
	{
		return active;
	}

	public void setActive(boolean pActive)
	{
		active = pActive;
	}

	public int getCurDebt()
	{
		return curDebt;
	}

	public void setCurDebt(int pCurDebt)
	{
		curDebt = pCurDebt;
	}

	public int getCurInterest()
	{
		return curInterest;
	}

	public void setCurInterest(int pCurInterest)
	{
		curInterest = pCurInterest;
	}

	@XmlTransient
	public String getName()
	{
		return name;
	}

	public Integer getId()
	{
		return id;
	}

	// Correctif sécurité (audit) : accesseur manquant, nécessaire pour vérifier côté
	// serveur qu'un joueur appartient bien à la partie visée avant toute action
	// (voir GameService.recordEvent/deletePlayer/renamePlayer) - sans lui, rien
	// n'empêchait de manipuler un joueur d'une AUTRE partie en devinant simplement
	// son identifiant.
	public Game getGame()
	{
		return game;
	}

	public boolean hasVisitedBank()
	{
		return visitedBank;
	}

	public boolean isVisitedBank()
	{
		return visitedBank;
	}

	public void setVisitedBank(boolean pVisitedBank)
	{
		visitedBank = pVisitedBank;
	}

	public int getGoodsCount()
	{
		return goodsCount;
	}

	public void setGoodsCount(final int pGoodsCount)
	{
		goodsCount = pGoodsCount;
	}

	public int getWeakGoods()
	{
		return weakGoods;
	}

	public void setWeakGoods(final int pWeakGoods)
	{
		weakGoods = pWeakGoods;
	}

	public int getMediumGoods()
	{
		return mediumGoods;
	}

	public void setMediumGoods(final int pMediumGoods)
	{
		mediumGoods = pMediumGoods;
	}

	public int getStrongGoods()
	{
		return strongGoods;
	}

	public void setStrongGoods(final int pStrongGoods)
	{
		strongGoods = pStrongGoods;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		// To be used only in the CLI version
		return "#" + getId() + " - " + getName() + (isActive() ? (getCurDebt() > 0 ? " - debt " + getCurDebt() + " - interest " + getCurInterest() : "") : " INACTIVE"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$
	}

	public void setName(String pName)
	{
		name = pName;
	}
}
